### PR TITLE
Document `pdex.bin` file format and improve conversion script

### PR DESCRIPTION
**Pull request by castholm**
I documented the `pdex.bin` file format. It is essentially a stripped-down ELF file consisting of metadata, a program segment and relocation entries.

I also rewrote `pdex2elf.py`, which did not actually work with modern `pdex.bin` files. I'm late to the Playdate game but I suspect (much) older versions of the SDK produced executable files in a much different format from what is in use currently.

The new `pdex2elf.py` script creates well-formed ELF file that can be analyzed by readelf or objdump and decompiled by Ghidra, and it can even be compiled back by `pdc` into a bit-for-bit idential copy of the original `pdex.bin`. I tested it with both some of my own WIP games as well as some non-encrypted games from the catalog and they round-tripped perfectly.

~It is a PowerShell script which I expect to be a bit controversial 😛 but PS is the only shell scripting-like language I'm proficient in so take it for what it is. If you would like to port the functionality to Python or whatever you have my blessing.~ Update: I've now ported it to Python.

### CODE REVIEW

**Comment by castholm** [comment]
@jaames Pinging just in case you haven't yet seen this PR.

**Comment by gatesphere** [comment]
As of SDK 2.5.0, pdc now supports multi-segment pdex.elf files.  Unknown if @castholm's script above will need any adjustments for this.

**Comment by castholm** [comment]
I believe that multi-segment fix is just so that the `pdc` compiler itself properly reads all segements in the input ELF file. It shouldn't have any effects on the `pdex.bin` format itself or the script.

**Comment by castholm** [comment]
Ported the PowerShell script to Python.

**Pull request merged**
